[2020-05-07 18:54:40,695|DEBUG|D:\Cloud\CloudStation\SJ\SJVA\plugin\plex\plugin.py:45] plugin_load:plex
[2020-05-07 19:11:36,252|DEBUG|plugin.py:46] plugin_load:plex
[2020-05-07 19:17:18,898|DEBUG|plugin.py:72] DETAIL plex setting
[2020-05-07 19:28:34,725|DEBUG|plugin.py:72] DETAIL plex setting
[2020-05-07 19:28:38,673|DEBUG|plugin.py:72] DETAIL plex tivimate
[2020-05-07 19:28:40,076|DEBUG|plugin.py:72] DETAIL plex lc
[2020-05-07 19:38:58,740|ERROR|logic.py:829] Exception:HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb3d40430>: Failed to establish a new connection: [Errno 111] Connection refused',))
[2020-05-07 19:38:58,746|ERROR|logic.py:830] Traceback (most recent call last):
  File "/home/coder/project/SJ/SJVA2/plugin/plex/logic.py", line 727, in make_xml
  File "/usr/local/lib/python2.7/site-packages/plexapi/server.py", line 102, in __init__
    data = self.query(self.key, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/plexapi/server.py", line 343, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb3d40430>: Failed to establish a new connection: [Errno 111] Connection refused',))

[2020-05-07 19:44:00,300|DEBUG|plugin.py:72] DETAIL plex setting
[2020-05-07 19:44:03,226|DEBUG|plugin.py:72] DETAIL plex plugin
[2020-05-07 23:19:59,114|DEBUG|plugin.py:46] plugin_load:plex
[2020-05-08 05:19:58,566|DEBUG|plugin.py:54] plugin_unload:plex
[2020-05-08 05:21:16,382|DEBUG|plugin.py:46] plugin_load:plex
[2020-05-08 11:22:05,811|DEBUG|plugin.py:54] plugin_unload:plex
[2020-05-08 11:23:18,215|DEBUG|plugin.py:46] plugin_load:plex
[2020-05-08 12:12:50,233|DEBUG|plugin.py:46] plugin_load:plex
[2020-05-08 18:13:03,099|DEBUG|plugin.py:54] plugin_unload:plex
[2020-05-08 18:13:54,235|DEBUG|plugin.py:46] plugin_load:plex
[2020-05-09 00:14:22,701|DEBUG|plugin.py:54] plugin_unload:plex
[2020-05-09 00:15:13,299|DEBUG|plugin.py:46] plugin_load:plex
[2020-05-09 06:15:53,763|DEBUG|plugin.py:54] plugin_unload:plex
[2020-05-09 06:16:38,462|DEBUG|plugin.py:46] plugin_load:plex
[2020-05-09 12:16:48,897|DEBUG|plugin.py:54] plugin_unload:plex
[2020-05-09 12:17:32,766|DEBUG|plugin.py:46] plugin_load:plex
[2020-05-09 18:17:56,877|DEBUG|plugin.py:54] plugin_unload:plex
[2020-05-09 18:18:37,236|DEBUG|plugin.py:46] plugin_load:plex
[2020-05-10 00:19:22,640|DEBUG|plugin.py:54] plugin_unload:plex
[2020-05-10 00:20:02,979|DEBUG|plugin.py:46] plugin_load:plex
[2020-05-10 06:20:34,463|DEBUG|plugin.py:54] plugin_unload:plex
[2020-05-10 06:21:12,344|DEBUG|plugin.py:46] plugin_load:plex
[2020-05-10 12:21:25,839|DEBUG|plugin.py:54] plugin_unload:plex
[2020-05-10 12:22:12,610|DEBUG|plugin.py:46] plugin_load:plex
[2020-05-10 18:22:51,602|DEBUG|plugin.py:54] plugin_unload:plex
[2020-05-10 18:23:35,962|DEBUG|plugin.py:46] plugin_load:plex
[2020-05-11 00:24:15,413|DEBUG|plugin.py:54] plugin_unload:plex
[2020-05-11 00:25:19,188|DEBUG|plugin.py:46] plugin_load:plex
[2020-05-11 06:25:56,672|DEBUG|plugin.py:54] plugin_unload:plex
[2020-05-11 06:26:55,728|DEBUG|plugin.py:46] plugin_load:plex
[2020-05-11 12:27:52,176|DEBUG|plugin.py:54] plugin_unload:plex
[2020-05-11 12:28:43,150|DEBUG|plugin.py:46] plugin_load:plex
